import type { ExplainMessages } from '@wzo/regex-diagram'

// Chinese message table for the core's formatExplain — a plain translation
// object, one template string per key. This is exactly what a library consumer
// passes to localize the explanation; the panel just hands it to formatExplain.
export const EXPLAIN_ZH: ExplainMessages = {
    char: '字符 "{value}"',
    space: '空格',
    text: '文本 "{value}"',
    csAny: '任意字符（换行除外）',
    csDigit: '数字（0-9）',
    csDigitNeg: '非数字字符',
    csWord: '单词字符（字母、数字或下划线）',
    csWordNeg: '非单词字符',
    csSpace: '空白字符',
    csSpaceNeg: '非空白字符',
    csProperty: '具有 Unicode 属性 {raw} 的字符',
    classEmpty: '什么都不匹配',
    classEmptyNeg: '任意字符',
    classOneOf: '下列之一：{parts}',
    classExcept: '除以下之外的任意字符：{parts}',
    listSep: '、',
    classExpr: '集合运算字符类（见图）',
    anchorStart: '字符串开头（带 m 标志时为行首）',
    anchorEnd: '字符串结尾（带 m 标志时为行尾）',
    wordBoundary: '单词边界',
    notWordBoundary: '非单词边界的位置',
    followedBy: '后接',
    notFollowedBy: '后面不接',
    precededBy: '前面是',
    notPrecededBy: '前面不是',
    qStar: '重复零次或多次',
    qPlus: '重复一次或多次',
    qMin: '重复 {min} 次或更多',
    qOptional: '可选（零次或一次）',
    qExact: '恰好重复 {n} 次',
    qRange: '重复 {min} 到 {max} 次',
    lazy: '{base}（懒惰）',
    groupNamed: '捕获组 #{index}（命名为 "{name}"）',
    group: '捕获组 #{index}',
    groupNonCapturing: '非捕获组',
    backref: '反向引用',
    backrefTo: '对捕获组 #{index} 的反向引用',
    option: '选项 {n}',
    withColon: '{text}：',
}
